import CodeIcon from '@mui/icons-material/Code';
import type { ToolRegistryEntry } from '../toolRegistryTypes';

const tool: ToolRegistryEntry = {
    route: "/developer-tools/graphql-to-fragment-matcher",
    navName: "GraphQL to Fragment Matcher",
    navDescription: "Generate Apollo's IntrospectionFragmentMatcher JSON.",
    name: "GraphQL Schema to Fragment Matcher Converter",
    description: "Paste a GraphQL SDL schema to instantly generate Apollo Client's classic IntrospectionFragmentMatcher JSON shape for every interface and union in your schema. Free online developer tool.",
    navCategory: "Developer Tools",
    shellCategory: "Developer Tools",
    icon: <CodeIcon fontSize="large" color="primary"/>,
    seoTitle: "GraphQL to Fragment Matcher Converter - Generate Apollo Matcher JSON Online",
    seoDescription: "Free online GraphQL to fragment matcher converter. Paste a GraphQL SDL schema to instantly generate Apollo Client's IntrospectionFragmentMatcher JSON for interfaces and unions.",
    keywords: ["graphql to fragment matcher", "apollo introspectionfragmentmatcher generator", "graphql union possibletypes", "graphql interface fragment matching", "graphql sdl to fragment matcher"],
    ogTitle: "GraphQL to Fragment Matcher Converter - Generate Apollo Matcher JSON Online | ToolZoneX",
    ogDescription: "Paste a GraphQL SDL schema to instantly generate Apollo's fragment matcher JSON.",
    schemaName: "GraphQL Schema to Fragment Matcher Converter",
    schemaDescription: "Paste a GraphQL SDL schema to instantly generate Apollo Client's IntrospectionFragmentMatcher JSON.",
    applicationCategory: "DeveloperApplication",
    currency: "INR",
    faqs: [{ question: "Is this still relevant for newer versions of Apollo Client?", answer: "Apollo Client 3+ generally recommends possibleTypes generated by @graphql-codegen/fragment-matcher instead of the older IntrospectionFragmentMatcher class, but the underlying data — which concrete types satisfy which interface or union — is the same, so this output is still useful as a reference or for projects still on the classic API." }, { question: "What if my schema has no interfaces or unions?", answer: "The output's types array will simply be empty — there's nothing to resolve possible types for without at least one interface or union in the schema." }, { question: "Is my schema uploaded anywhere?", answer: "No — parsing and resolution happen entirely client-side in your browser. Nothing you paste is sent to a server." }],
    extraSchemaFields: undefined,
    isHub: false,
};

export default tool;
