import CampaignIcon from '@mui/icons-material/Campaign';
import type { ToolRegistryEntry } from '../toolRegistryTypes';

const tool: ToolRegistryEntry = {
    route: "/finance/cpa-calculator",
    navName: "CPA Calculator",
    navDescription: "Cost per acquisition from spend & conversions.",
    name: "CPA Calculator",
    description: "Calculate Cost Per Acquisition (CPA) from total marketing or ad spend and the number of customers or conversions acquired.",
    navCategory: "Finance",
    shellCategory: "Finance",
    icon: <CampaignIcon fontSize="large" color="primary"/>,
    seoTitle: "CPA Calculator - Cost Per Acquisition Calculator",
    seoDescription: "Free CPA calculator. Enter total ad spend and number of conversions to calculate Cost Per Acquisition (CPA).",
    keywords: ["cpa calculator", "cost per acquisition calculator", "customer acquisition cost calculator", "cpa formula", "marketing cpa calculator"],
    ogTitle: "CPA Calculator - Cost Per Acquisition Calculator | ToolZoneX",
    ogDescription: "Calculate Cost Per Acquisition from total ad spend and conversions.",
    schemaName: "CPA Calculator",
    schemaDescription: "Calculate Cost Per Acquisition (CPA) from total marketing or ad spend and the number of customers or conversions acquired.",
    applicationCategory: "FinanceApplication",
    currency: "USD",
    faqs: [{ question: "What is a good CPA?", answer: "There's no universal number — a good CPA is one that's comfortably below the customer lifetime value (CLV) generated by that customer. Compare CPA against CLV to judge whether acquisition spend is actually profitable, not just against a fixed benchmark." }, { question: "Is CPA the same as CAC?", answer: "They're essentially the same concept — Customer Acquisition Cost (CAC) is another common term for Cost Per Acquisition. Some teams use CAC to include all sales and marketing costs, while CPA sometimes refers narrowly to ad spend alone; check how your organization defines each term." }, { question: "Does CPA account for what happens after the sale?", answer: "No — CPA only measures the cost of the initial acquisition. Pair it with the Customer Lifetime Value Calculator to see whether the acquired customer generates enough revenue over time to justify that cost." }],
    extraSchemaFields: undefined,
    isHub: false,
};

export default tool;
