import BadgeIcon from '@mui/icons-material/Badge';
import type { ToolRegistryEntry } from '../toolRegistryTypes';

const tool: ToolRegistryEntry = {
    route: "/generators/nickname-finder",
    navName: "Nickname Finder",
    navDescription: "Generate nickname suggestions.",
    name: "Nickname Finder - Nickname Generator",
    description: "Type in a name and get 8-10 nickname suggestions, combining common English diminutives with rule-based shortening and suffix patterns.",
    navCategory: "Generators",
    shellCategory: "Generators",
    icon: <BadgeIcon fontSize="large" color="primary"/>,
    seoTitle: "Nickname Finder - Nickname Generator Online Free",
    seoDescription: "Free online nickname finder and generator. Type a name and get 8-10 nickname suggestions from common diminutives and rule-based patterns.",
    keywords: ["nickname finder", "nickname generator", "nickname maker", "cute nickname generator", "find a nickname", "nickname ideas"],
    ogTitle: "Nickname Finder - Nickname Generator Online Free | ToolZoneX",
    ogDescription: "Type in a name and get 8-10 nickname suggestions from common diminutives and rule-based patterns.",
    schemaName: "Nickname Finder",
    schemaDescription: "Generate nickname suggestions for a name using a curated dictionary and rule-based patterns.",
    applicationCategory: "EntertainmentApplication",
    currency: "INR",
    faqs: [{ question: "Are these nicknames generated by AI?", answer: "No — this is a rule-based generator. It combines a curated dictionary of common English nicknames with fixed transformation patterns (shortening, common suffixes, etc.), so the same name always produces the same suggestions." }, { question: "Why do some names get more \"real\" nicknames than others?", answer: "Well-known names like William or Elizabeth have long-established traditional nicknames included in our dictionary. For names not in that list, the tool relies entirely on generic pattern-based rules, which can feel more playful than traditional." }, { question: "Does it work for names in other languages?", answer: "The dictionary is focused on common English names, but the rule-based patterns (shortening, adding \"-y\" or \"-ster\", etc.) will still generate suggestions for most names using the Latin alphabet." }],
    extraSchemaFields: undefined,
    isHub: false,
    noindex: true,
};

export default tool;
