import PaletteIcon from '@mui/icons-material/Palette';
import type { ToolRegistryEntry } from '../toolRegistryTypes';

const tool: ToolRegistryEntry = {
    route: "/generators/random-color-generator",
    navName: "Random Color Generator",
    navDescription: "Generate random HEX, RGB & HSL colors.",
    name: "Random Color Generator - HEX, RGB & HSL",
    description: "Generate random colors instantly with HEX, RGB, and HSL values shown side by side, plus a copy button for each format.",
    navCategory: "Generators",
    shellCategory: "Generators",
    icon: <PaletteIcon fontSize="large" color="primary"/>,
    seoTitle: "Random Color Generator - HEX, RGB & HSL Codes",
    seoDescription: "Generate random colors instantly with HEX, RGB, and HSL values shown side by side. Free online tool with one-click copy and a multi-color palette option.",
    keywords: ["random color generator", "random hex color", "random color palette generator", "random rgb color"],
    ogTitle: "Random Color Generator - HEX, RGB & HSL Codes | ToolZoneX",
    ogDescription: "Generate random colors instantly with HEX, RGB, and HSL values shown side by side.",
    schemaName: "Random Color Generator",
    schemaDescription: "Generate random colors instantly with HEX, RGB, and HSL values shown side by side, plus a copy button for each format.",
    applicationCategory: "DesignApplication",
    currency: "INR",
    faqs: [{ question: "Are the colors truly random?", answer: "Yes — each color is generated by randomly choosing red, green, and blue values independently, giving every one of the 16.7 million possible RGB colors an equal chance of appearing." }, { question: "What's the difference between HEX, RGB, and HSL?", answer: "HEX and RGB both describe a color by its red, green, and blue components — HEX as a compact hexadecimal code and RGB as three decimal numbers. HSL describes the same color using hue, saturation, and lightness instead." }, { question: "Can I generate more than one color at a time?", answer: "Yes — set the \"Colors to generate\" field to any number up to 12 to create a small random palette in one click." }],
    extraSchemaFields: undefined,
    isHub: false,
    noindex: true,
};

export default tool;
