import PictureAsPdfIcon from '@mui/icons-material/PictureAsPdf';
import type { ToolRegistryEntry } from '../toolRegistryTypes';

const tool: ToolRegistryEntry = {
    route: "/tools/pdf-outline-viewer",
    navName: "PDF Outline Viewer",
    navDescription: "View the structural outline of a PDF.",
    name: "PDF Outline Viewer",
    description: "View the document outline (table of contents structure) of any PDF. Browse the full heading hierarchy with page numbers. Free, private, runs entirely in your browser.",
    navCategory: "PDF Tools",
    shellCategory: "Tools",
    icon: <PictureAsPdfIcon fontSize="large" color="primary"/>,
    seoTitle: "PDF Outline Viewer - View PDF Document Structure Online",
    seoDescription: "Free online PDF outline viewer. See the full document structure, heading hierarchy, and table of contents with page numbers.",
    keywords: ["pdf outline", "view pdf structure", "pdf document outline", "pdf headings", "pdf table of contents viewer", "pdf structure viewer"],
    ogTitle: "PDF Outline Viewer - View PDF Document Structure Online | ToolZoneX",
    ogDescription: "View the full document structure, heading hierarchy, and table of contents of any PDF with page numbers.",
    schemaName: "PDF Outline Viewer",
    schemaDescription: "View the document outline and heading hierarchy of any PDF.",
    applicationCategory: "UtilityApplication",
    currency: "USD",
    faqs: [{ question: "What is the difference between an outline and bookmarks?", answer: "In PDF terminology they are the same thing — the document outline is the official PDF specification name, while 'bookmarks' is the common term used by most viewers." }, { question: "Why is my outline empty?", answer: "The PDF was likely saved without outline entries. Many basic PDF exporters and scanners do not create outlines. They must be explicitly generated by the authoring software." }, { question: "Is my file uploaded anywhere?", answer: "No — outline extraction runs entirely in your browser." }],
    extraSchemaFields: undefined,
    isHub: false,
};

export default tool;
