import PictureAsPdfIcon from '@mui/icons-material/PictureAsPdf';
import type { ToolRegistryEntry } from '../toolRegistryTypes';

const tool: ToolRegistryEntry = {
    route: "/tools/pdf-bookmark-viewer",
    navName: "PDF Bookmark Viewer",
    navDescription: "View PDF bookmarks and table of contents.",
    name: "PDF Bookmark Viewer",
    description: "View all bookmarks and table of contents in a PDF file. Browse the full bookmark hierarchy with page references. Free, private, runs entirely in your browser.",
    navCategory: "PDF Tools",
    shellCategory: "Tools",
    icon: <PictureAsPdfIcon fontSize="large" color="primary"/>,
    seoTitle: "PDF Bookmark Viewer - View PDF Bookmarks & Outlines Online",
    seoDescription: "Free online PDF bookmark viewer. See all bookmarks and table of contents in any PDF with page references. Browse the full hierarchy.",
    keywords: ["pdf bookmarks", "view pdf bookmarks", "pdf outline viewer", "pdf table of contents", "check pdf bookmarks", "pdf bookmark list"],
    ogTitle: "PDF Bookmark Viewer - View PDF Bookmarks & Outlines Online | ToolZoneX",
    ogDescription: "View all bookmarks and table of contents in a PDF file. Browse the full bookmark hierarchy with page references.",
    schemaName: "PDF Bookmark Viewer",
    schemaDescription: "View all bookmarks and table of contents in a PDF file with page references.",
    applicationCategory: "UtilityApplication",
    currency: "USD",
    faqs: [{ question: "Why does it say no bookmarks were found?", answer: "Not all PDFs include bookmarks. They must be manually added by the PDF creator or generated by the authoring tool — scanners and basic converters typically do not add them." }, { question: "Can I click on a bookmark to jump to that page?", answer: "No — this is a viewer that extracts and displays the bookmark data. To navigate by bookmark, open the PDF in a PDF reader application." }, { question: "Is my file uploaded anywhere?", answer: "No — bookmark extraction happens entirely in your browser." }],
    extraSchemaFields: undefined,
    isHub: false,
    noindex: true,
};

export default tool;
