import PictureAsPdfIcon from '@mui/icons-material/PictureAsPdf';
import type { ToolRegistryEntry } from '../toolRegistryTypes';

const tool: ToolRegistryEntry = {
    route: "/tools/extract-pdf-bookmarks",
    navName: "Extract PDF Bookmarks",
    navDescription: "Extract bookmarks and outlines from a PDF.",
    name: "Extract PDF Bookmarks Online Free",
    description: "Extract all bookmarks and outlines from a PDF, display them as a hierarchy, and download as text or JSON. Free, private, runs entirely in your browser.",
    navCategory: "PDF Tools",
    shellCategory: "Tools",
    icon: <PictureAsPdfIcon fontSize="large" color="primary"/>,
    seoTitle: "Extract PDF Bookmarks Online Free",
    seoDescription: "Free online tool to extract PDF bookmarks and outlines. Browse the full hierarchy and download as text or JSON.",
    keywords: ["extract pdf bookmarks", "get pdf bookmarks", "pdf outline extractor", "pdf bookmarks to text"],
    ogTitle: "Extract PDF Bookmarks Online Free | ToolZoneX",
    ogDescription: "Extract all bookmarks and outlines from a PDF, display them as a hierarchy, and download as text or JSON.",
    schemaName: "Extract PDF Bookmarks",
    schemaDescription: "Extract all bookmarks and outlines from a PDF and display them as a hierarchy.",
    applicationCategory: "UtilityApplication",
    currency: "USD",
    faqs: [{ question: "What if no bookmarks are found?", answer: "Not all PDFs include bookmarks — they must be manually added by the author or generated by the creating software." }, { question: "Does this modify the PDF?", answer: "No — extraction is read-only. Your original file is never changed." }, { question: "Is my file uploaded anywhere?", answer: "No — everything happens in your browser." }],
    extraSchemaFields: undefined,
    isHub: false,
    noindex: true,
};

export default tool;
