import PictureAsPdfIcon from '@mui/icons-material/PictureAsPdf';
import type { ToolRegistryEntry } from '../toolRegistryTypes';

const tool: ToolRegistryEntry = {
    route: "/tools/add-qr-code-to-pdf",
    navName: "Add QR Code to PDF",
    navDescription: "Add a scannable QR code to every PDF page.",
    name: "Add QR Code to PDF Online Free",
    description: "Add a QR code image to every page of a PDF. Enter the URL or text and position. Free, private, runs entirely in your browser.",
    navCategory: "PDF Tools",
    shellCategory: "Tools",
    icon: <PictureAsPdfIcon fontSize="large" color="primary"/>,
    seoTitle: "Add QR Code to PDF Online Free",
    seoDescription: "Add a QR code image to every page of a PDF online. Enter the URL or text and position. Free, private, runs in your browser.",
    keywords: ["add qr code to pdf", "pdf qr code", "insert qr code pdf", "qr code on pdf"],
    ogTitle: "Add QR Code to PDF Online Free | ToolZoneX",
    ogDescription: "Add a QR code image to every page of a PDF online. Free, private, runs in your browser.",
    schemaName: "Add Qr Code To Pdf",
    schemaDescription: "Add a QR code image to every page of a PDF.",
    applicationCategory: "UtilityApplication",
    currency: "USD",
    faqs: [{ question: "Is the same QR code on every page?", answer: "Yes — the content you enter is encoded once and placed at the same spot on each page." }, { question: "Does this need an internet connection?", answer: "The QR image is generated by an external QR service, so you need to be online when you click the button. The PDF itself is never uploaded." }, { question: "Is my file uploaded anywhere?", answer: "No — only the QR text is sent to the QR generation service; your PDF is processed in your browser." }],
    extraSchemaFields: undefined,
    isHub: false,
};

export default tool;
