import fs from 'fs';
import path from 'path';

// Define the root URL of your static site
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://punit461.github.io/toolzonex';

async function generateSitemap() {
  const publicPath = path.join(process.cwd(), 'out');
  const appPath = path.join(process.cwd(), 'src', 'app');
  
  // Make sure 'out' directory exists (it should, this runs postbuild)
  if (!fs.existsSync(publicPath)) {
    fs.mkdirSync(publicPath, { recursive: true });
  }

  // We will crawl the `out` directory to find all .html files generated by next export
  const urls = [];

  function crawlDir(directory, basePath = '') {
    const files = fs.readdirSync(directory);

    for (const file of files) {
      const fullPath = path.join(directory, file);
      const stat = fs.statSync(fullPath);

      if (stat.isDirectory()) {
        crawlDir(fullPath, `${basePath}/${file}`);
      } else if (file.endsWith('.html') && file !== '404.html') {
        let route = `${basePath}/${file.replace('.html', '')}`;
        // Clean up index routes
        if (route.endsWith('/index')) {
          route = route.replace('/index', '');
        }
        if (route === '') {
          route = '/';
        }
        urls.push(route);
      }
    }
  }

  crawlDir(publicPath);

  // Filter out any duplicates
  const uniqueUrls = [...new Set(urls)];

  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${uniqueUrls
  .map((url) => {
    return `  <url>
    <loc>${SITE_URL}${url}</loc>
    <lastmod>${new Date().toISOString()}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>${url === '/' ? '1.0' : '0.8'}</priority>
  </url>`;
  })
  .join('\n')}
</urlset>`;

  fs.writeFileSync(path.join(publicPath, 'sitemap.xml'), sitemap);
  console.log('✅ sitemap.xml generated successfully in /out/sitemap.xml');

  // Also generate robots.txt
  const robots = `User-agent: *
Allow: /

Sitemap: ${SITE_URL}/sitemap.xml
`;
  fs.writeFileSync(path.join(publicPath, 'robots.txt'), robots);
  console.log('✅ robots.txt generated successfully in /out/robots.txt');
}

generateSitemap();
