'use client';

import { useMemo, useState } from 'react';
import { Box, TextField, Typography, Paper, Button } from '@mui/material';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import CalculatorShell from '../../components/CalculatorShell';
import AdSenseUnit from '../../components/AdSenseUnit';

const BrowserconfigGeneratorContent = () => {
  const [small, setSmall] = useState('/mstile-70x70.png');
  const [medium, setMedium] = useState('/mstile-150x150.png');
  const [wide, setWide] = useState('/mstile-310x150.png');
  const [large, setLarge] = useState('/mstile-310x310.png');
  const [tileColor, setTileColor] = useState('#2b5797');
  const [copied, setCopied] = useState(false);

  const xml = useMemo(() => {
    return `<?xml version="1.0" encoding="utf-8"?>
<browserconfig>
  <msapplication>
    <tile>
      <square70x70logo src="${small}"/>
      <square150x150logo src="${medium}"/>
      <wide310x150logo src="${wide}"/>
      <square310x310logo src="${large}"/>
      <TileColor>${tileColor}</TileColor>
    </tile>
  </msapplication>
</browserconfig>`;
  }, [small, medium, wide, large, tileColor]);

  const copyResult = async () => {
    try {
      await navigator.clipboard.writeText(xml);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {}
  };

  return (
    <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: '1fr 1fr' }, gap: 4 }}>
      <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
        <TextField label="Small Tile (70x70)" value={small} onChange={(e) => setSmall(e.target.value)} fullWidth />
        <TextField label="Medium Tile (150x150)" value={medium} onChange={(e) => setMedium(e.target.value)} fullWidth />
        <TextField label="Wide Tile (310x150)" value={wide} onChange={(e) => setWide(e.target.value)} fullWidth />
        <TextField label="Large Tile (310x310)" value={large} onChange={(e) => setLarge(e.target.value)} fullWidth />
        <TextField label="Tile Background Color" type="color" value={tileColor} onChange={(e) => setTileColor(e.target.value)} sx={{ width: { xs: '100%', sm: '50%' } }} />
      </Box>

      <Box>
        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 1 }}>
          <Typography variant="subtitle1" fontWeight="600">browserconfig.xml:</Typography>
          <Button size="small" startIcon={<ContentCopyIcon />} onClick={copyResult}>
            {copied ? 'Copied!' : 'Copy'}
          </Button>
        </Box>
        <Paper variant="outlined" sx={{ p: 2, fontFamily: 'monospace', fontSize: '0.8rem', whiteSpace: 'pre-wrap', wordBreak: 'break-all', bgcolor: 'action.hover', minHeight: 240 }}>
          {xml}
        </Paper>
      </Box>
    </Box>
  );
};

const BrowserconfigGenerator = () => {
  const content = (
    <>
      <Typography variant="h2">How to Use the Browserconfig.xml Generator</Typography>
      <Typography variant="body1">
        <code>browserconfig.xml</code> tells Windows and Microsoft Edge which images and background color to use
        when a visitor pins your site to their Windows Start screen or taskbar. Provide the four standard tile
        image sizes — 70x70 (small), 150x150 (medium), 310x150 (wide), and 310x310 (large) — plus a tile
        background color, then copy the generated XML into a file named <code>browserconfig.xml</code> at the
        root of your site.
      </Typography>

      <Typography variant="h2">Example</Typography>
      <Typography variant="body1">
        Once <code>browserconfig.xml</code> is published at your domain root, a browser looking for it will
        automatically pick up the tile images and color without any extra <code>&lt;meta&gt;</code> tags needed
        in your HTML.
      </Typography>

      <Typography variant="h2">Common Use Cases</Typography>
      <Box sx={{ typography: 'body1' }}>
        <ul>
          <li>Customizing the Windows tile image and color shown when a site is pinned to the Start screen.</li>
          <li>Passing browserconfig-related checks in SEO or site-completeness audit tools.</li>
          <li>Filling out a favicon/icon package generated by a build tool or site template.</li>
        </ul>
      </Box>

      <Typography variant="h2">FAQs</Typography>
      <Box sx={{ typography: 'body1' }}>
        <ul>
          <li><strong>Is browserconfig.xml still relevant?</strong> It&apos;s a somewhat legacy, Windows-specific feature with a shrinking practical impact as pinned-tile Start screens have become less common, but it&apos;s still checked by some SEO and site-auditing tools and included by default in many favicon-generator templates.</li>
          <li><strong>Where does the file need to live?</strong> At the root of your domain, e.g. <code>https://example.com/browserconfig.xml</code>, so Windows can find it automatically.</li>
          <li><strong>Do I need all four tile sizes?</strong> Providing all four covers every tile size Windows might display; if you skip one, that size simply falls back to a default tile rather than causing an error.</li>
        </ul>
      </Box>
    </>
  );

  return (
    <CalculatorShell url="/developer-tools/browserconfig-generator" content={content}>
      <BrowserconfigGeneratorContent />
      <Box sx={{ mt: 4 }}><AdSenseUnit /></Box>
    </CalculatorShell>
  );
};

export default BrowserconfigGenerator;
