'use client';

import { useState } from 'react';
import { Box, TextField, Typography, Button, Paper, IconButton, FormControl, InputLabel, Select, MenuItem, Alert } from '@mui/material';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import AddIcon from '@mui/icons-material/Add';
import DeleteIcon from '@mui/icons-material/Delete';
import CalculatorShell from '../../components/CalculatorShell';
import AdSenseUnit from '../../components/AdSenseUnit';

interface RobotsRule {
  type: 'allow' | 'disallow';
  path: string;
}

const RobotsTxtGeneratorContent = () => {
  const [siteUrl, setSiteUrl] = useState('https://example.com');
  const [rules, setRules] = useState<RobotsRule[]>([
    { type: 'disallow', path: '/admin/' },
    { type: 'allow', path: '/' },
  ]);
  const [crawlDelay, setCrawlDelay] = useState('');
  const [sitemapUrl, setSitemapUrl] = useState('');
  const [output, setOutput] = useState('');
  const [copied, setCopied] = useState(false);

  const addRule = () => {
    setRules([...rules, { type: 'disallow', path: '' }]);
  };

  const removeRule = (index: number) => {
    setRules(rules.filter((_, i) => i !== index));
  };

  const updateRule = (index: number, field: keyof RobotsRule, value: string) => {
    const updated = [...rules];
    updated[index] = { ...updated[index], [field]: value };
    setRules(updated);
  };

  const generate = () => {
    const lines: string[] = [];
    lines.push('# Robots.txt generated by ToolZoneX');
    lines.push(`# Site: ${siteUrl || 'https://example.com'}`);
    lines.push('');
    lines.push('User-agent: *');
    lines.push('');

    for (const rule of rules) {
      if (rule.path.trim()) {
        if (rule.type === 'allow') {
          lines.push(`Allow: ${rule.path}`);
        } else {
          lines.push(`Disallow: ${rule.path}`);
        }
      }
    }

    if (crawlDelay.trim()) {
      lines.push('');
      lines.push(`Crawl-delay: ${crawlDelay}`);
    }

    if (sitemapUrl.trim()) {
      lines.push('');
      lines.push(`Sitemap: ${sitemapUrl}`);
    }

    lines.push('');
    setOutput(lines.join('\n'));
    setCopied(false);
  };

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {}
  };

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
      <TextField
        label="Website URL"
        value={siteUrl}
        onChange={(e) => setSiteUrl(e.target.value)}
        placeholder="https://example.com"
        fullWidth
      />

      <Box>
        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
          <Typography variant="subtitle1" fontWeight={600}>Rules</Typography>
          <Button size="small" startIcon={<AddIcon />} onClick={addRule}>Add Rule</Button>
        </Box>
        {rules.map((rule, idx) => (
          <Box key={idx} sx={{ display: 'flex', gap: 1, mb: 1, alignItems: 'center' }}>
            <FormControl size="small" sx={{ minWidth: 120 }}>
              <InputLabel>Type</InputLabel>
              <Select
                value={rule.type}
                label="Type"
                onChange={(e) => updateRule(idx, 'type', e.target.value)}
              >
                <MenuItem value="allow">Allow</MenuItem>
                <MenuItem value="disallow">Disallow</MenuItem>
              </Select>
            </FormControl>
            <TextField
              size="small"
              value={rule.path}
              onChange={(e) => updateRule(idx, 'path', e.target.value)}
              placeholder="/path/"
              fullWidth
            />
            <IconButton onClick={() => removeRule(idx)} size="small" color="error">
              <DeleteIcon />
            </IconButton>
          </Box>
        ))}
      </Box>

      <TextField
        label="Crawl Delay (optional)"
        value={crawlDelay}
        onChange={(e) => setCrawlDelay(e.target.value)}
        placeholder="10"
        type="number"
        fullWidth
        helperText="Seconds between crawl requests (leave empty for default)"
      />

      <TextField
        label="Sitemap URL (optional)"
        value={sitemapUrl}
        onChange={(e) => setSitemapUrl(e.target.value)}
        placeholder="https://example.com/sitemap.xml"
        fullWidth
      />

      <Button variant="contained" onClick={generate} size="large">
        Generate robots.txt
      </Button>

      {output && (
        <Paper variant="outlined" sx={{ p: 2 }}>
          <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 1 }}>
            <Typography variant="subtitle1" fontWeight={600}>Generated robots.txt</Typography>
            <Button size="small" startIcon={<ContentCopyIcon />} onClick={copyToClipboard}>
              {copied ? 'Copied!' : 'Copy'}
            </Button>
          </Box>
          <Paper sx={{ p: 2, bgcolor: 'grey.50', fontFamily: 'monospace', whiteSpace: 'pre-wrap', overflow: 'auto' }}>
            {output}
          </Paper>
        </Paper>
      )}
    </Box>
  );
};

const RobotsTxtGenerator = () => {
  const content = (
    <>
      <Typography variant="h2">How to Use the Robots.txt Generator</Typography>
      <Typography variant="body1">
        Enter your website URL, add allow/disallow rules for the paths you want to control, and optionally set a crawl delay and sitemap URL. Click &quot;Generate&quot; to create a valid robots.txt file you can copy and paste into your website root.
      </Typography>

      <Typography variant="h2">Example</Typography>
      <Typography variant="body1">
        To block search engines from crawling your admin pages but allow the rest of your site, add a &quot;Disallow: /admin/&quot; rule and an &quot;Allow: /&quot; rule. The generated output will look like a standard robots.txt file.
      </Typography>

      <Typography variant="h2">FAQs</Typography>
      <Box sx={{ typography: 'body1' }}>
        <ul>
          <li><strong>Where do I put the robots.txt file?</strong> Upload it to the root directory of your website (e.g., https://example.com/robots.txt).</li>
          <li><strong>Does a robots.txt block all crawlers?</strong> No — it is a voluntary standard. Legitimate search engine bots respect it, but malicious bots may ignore it.</li>
          <li><strong>What is Crawl-delay?</strong> It tells compliant crawlers how many seconds to wait between requests to your site, helping reduce server load.</li>
        </ul>
      </Box>

      <Typography variant="h2">Common Use Cases</Typography>
      <Box sx={{ typography: 'body1' }}>
        <ul>
          <li>Blocking search engines from indexing admin or private areas of your site.</li>
          <li>Specifying the location of your sitemap for easier crawling.</li>
          <li>Controlling crawl rate to avoid overloading your server.</li>
        </ul>
      </Box>
    </>
  );

  return (
    <CalculatorShell url="/developer-tools/robots-txt-generator" content={content}>
      <RobotsTxtGeneratorContent />
      <Box sx={{ mt: 4 }}><AdSenseUnit /></Box>
    </CalculatorShell>
  );
};

export default RobotsTxtGenerator;
