'use client';

import { useState, useMemo } from 'react';
import { Box, TextField, Typography, Paper, InputAdornment } from '@mui/material';
import CalculatorShell from '../../components/CalculatorShell';
import AdSenseUnit from '../../components/AdSenseUnit';

const fmt = (n: number) =>
  new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(n);

const CPACalculator = () => {
  const [adSpend, setAdSpend] = useState('5000');
  const [conversions, setConversions] = useState('200');

  const cpa = useMemo(() => {
    const spend = parseFloat(adSpend) || 0;
    const count = parseFloat(conversions) || 0;
    return count > 0 ? spend / count : null;
  }, [adSpend, conversions]);

  const content = (
    <>
      <Typography variant="h2">How Cost Per Acquisition (CPA) Is Calculated</Typography>
      <Typography variant="body1">
        Cost Per Acquisition — sometimes shortened to CPA, not to be confused with the accounting
        designation Certified Public Accountant — measures how much it costs, on average, to acquire
        one customer or conversion. Divide total marketing or ad spend by the number of customers or
        conversions that spend generated to get the CPA.
      </Typography>
      <Box sx={{ my: 2, p: 2, bgcolor: 'action.hover', borderRadius: 1, fontFamily: 'monospace', fontSize: '0.9rem' }}>
        CPA = Total Ad Spend / Number of Conversions
      </Box>

      <Typography variant="h2">Example</Typography>
      <Typography variant="body1">
        Spending $5,000 on ads that generate 200 new customers gives a CPA of $25 per customer
        acquired. If the average customer is worth more than $25 in lifetime value, the acquisition
        spend is likely profitable.
      </Typography>

      <Typography variant="h2">Common Use Cases</Typography>
      <Box sx={{ typography: 'body1' }}>
        <ul>
          <li>Measuring the efficiency of a marketing or advertising campaign.</li>
          <li>Comparing acquisition costs across different channels or campaigns.</li>
          <li>Deciding whether a campaign&apos;s CPA is sustainable against customer lifetime value.</li>
          <li>Setting bidding or budget targets for paid acquisition channels.</li>
        </ul>
      </Box>

      <Typography variant="h2">FAQs</Typography>
      <Typography variant="h3">What is a good CPA?</Typography>
      <Typography variant="body1">
        There&apos;s no universal number — a good CPA is one that&apos;s comfortably below the customer
        lifetime value (CLV) generated by that customer. Compare CPA against CLV to judge whether
        acquisition spend is actually profitable, not just against a fixed benchmark.
      </Typography>
      <Typography variant="h3">Is CPA the same as CAC?</Typography>
      <Typography variant="body1">
        They&apos;re essentially the same concept — Customer Acquisition Cost (CAC) is another common
        term for Cost Per Acquisition. Some teams use CAC to include all sales and marketing costs,
        while CPA sometimes refers narrowly to ad spend alone; check how your organization defines each
        term.
      </Typography>
      <Typography variant="h3">Does CPA account for what happens after the sale?</Typography>
      <Typography variant="body1">
        No — CPA only measures the cost of the initial acquisition. Pair it with the Customer Lifetime
        Value Calculator to see whether the acquired customer generates enough revenue over time to
        justify that cost.
      </Typography>
    </>
  );

  return (
    <CalculatorShell url="/finance/cpa-calculator" content={content}>
      <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: '1fr 1fr' }, gap: 4 }}>
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
          <TextField
            label="Total Marketing / Ad Spend"
            type="number"
            value={adSpend}
            onChange={(e) => setAdSpend(e.target.value)}
            fullWidth
            slotProps={{ input: { startAdornment: <InputAdornment position="start">$</InputAdornment> } }}
          />
          <TextField
            label="Number of Customers / Conversions"
            type="number"
            value={conversions}
            onChange={(e) => setConversions(e.target.value)}
            fullWidth
          />
        </Box>

        <Box>
          <Paper sx={{ p: 3, textAlign: 'center', bgcolor: 'primary.main', color: 'white' }}>
            <Typography variant="body2">Cost Per Acquisition</Typography>
            <Typography variant="h3" fontWeight="bold">{cpa !== null ? fmt(cpa) : '--'}</Typography>
          </Paper>
        </Box>
      </Box>

      <Box sx={{ mt: 4 }}><AdSenseUnit /></Box>
    </CalculatorShell>
  );
};

export default CPACalculator;
